name: Publish TSCGame map

on:
  workflow_dispatch:

jobs:
  checkout-and-copy:
    name: checkout-and-copy
    runs-on: ubuntu-latest

    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: dirondin/pet-project-map
          path: './build'
          token: ${{ secrets.my_pat }}

      - name: Copy
        run: cp -r ./build ./tscgame_map

      - name: Push
        run: |
          git add -A
          git commit -m "Automated report"
          git push

    
      
